name: citronix
services:
  postgres:
    container_name: citronix_db
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=citronix'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=citronix'
    volumes:
      - C:/java project/pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  postgres_data:
    driver: local